### ISSUE TITLE
How to use GPU for inference

### ISSUE THREAD

**Issue by CHYjeremy** [deepmind/tapnet#40]
HI author of tapnet,

thanks for your great work.

I want to ask how could i use GPU for inference in your work. 

with normal setup, it reminds me "no GPU/TPU, falling back to cpu" when i actually have GPU available. 

Then i see that it seems i need correct version of jax, 
so i then create a new env, pip install the compatible version of jax as instructed in a link you provide, and then set up the remaining dependency as in requirement.txt. but i got this: 
"Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR" 
and 
"jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details."

do you know why is that? thanks a lot

**Comment by cdoersch** [comment]
Getting jax to install correctly on GPUs is a bit of an art form.  cudnn is required for recent versions of jax, and you should also check that cuda's bin is on your PATH.  But I'm no expert; you'd probably have better luck asking in the jax repo.

**Comment by ahsanMuh** [comment]
I followed the instructions provided on [Jax installation](https://github.com/google/jax/tree/364a245ab2fcc0a7c5187234e94c1a3a8d464c39#installation:~:text=pip%20installation%3A%20GPU%20(CUDA%2C%20installed%20via%20pip%2C%20easier)). The below snippet worked for me in a first try:
```
pip install --upgrade pip

# CUDA 12 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# CUDA 11 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by CHYjeremy** [comment]
thanks cdoersch.

Hi ahsanMuh,

thanks for your advice, but can you elaborate more? 

is it that, you first do the script you mentioned above, and then you pip install all requirement.txt that is specific to tapir?

what is the complete setup procedure for you to run tapir on Gpu?

**Comment by ahsanMuh** [comment]
First of all, I installed everything as mentioned on the tapnet repo. I was able to run inference but only on a **cpu**.

Then, I went to Jax repo as mentioned earlier. I do have the **nvidia-driver** installed with me. Then I just followed what I shared earlier, and on rerunning, everything works on a **gpu**.

I hope this helps. :)

**Comment by CHYjeremy** [comment]
thank you ahsanMuh
